
name: 'Setup'
description: 'Composite action to set up'


runs:
  using: 'composite'
  steps:
    - name: Setup test
      shell: bash
      run: |
        echo "Hello world for setup from action "
   
